import Navbar from '@/components/navbar';
import '@/styles/globals.scss'
import '@/styles/layout.scss'


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir='rtl'>
        <body>
          <Navbar />
        <main className='main-layout'>
          {children}
        </main>
        </body>
    </html>
  );
}
